

templates:

  - name: ingress
    version: 1.0.0
    body: |
      componentReleases:
      - name: metallb
        namespace: metallb
        component:
          name: ingress:metallb
          version: 1.0.0
      
      - name: metallb-pool
        namespace: metallb
        component:
          name: ingress:metallb-pool
          version: 1.0.0

      - name: ingress-nginx
        namespace: ingress-nginx
        component:
          name: ingress:ingress-nginx
          version: 1.0.0
      
      {{- if .Context.ingress.kubernetes.enabled }}
      - name: ingress-kubernetes
        namespace: ingress-nginx
        component:
          name: ingress:kubernetes
          version: 1.0.0
      {{- end }}