$schema: "http://json-schema.org/schema#"
type: object
additionalProperties: true
required:
  - ingress
properties:
  ingress:
    type: object
    additionalProperties: false
    required:
      - url
    properties:
      url:
        type: string
      kubernetes:
        type: object
        additionalProperties: false
        properties:
          enabled:
            type: boolean

