
templates:

  - name: system-base
    version: 1.0.0
    body: |
      templateReleases:
      - name: cert-manager
        template:
          name: cert/cert-manager
          version: 1.0.0

      - name: ingress
        template:
          name: ingress
          version: 1.0.0


