

templates:

  - name: ingress
    version: 1.0.0
    catalogs:
      - system
    parametersSchema:
      yaml:
        $schema: "http://json-schema.org/schema#"
        title: Ingress controller with load balancer
        description: |
          Stack managing ingress with Load Balancer and Ingress controller.
        type: object
        additionalProperties: false
        properties: {}
    contextSchema:
      yaml:
        $schema: "http://json-schema.org/schema#"
        type: object
        additionalProperties: true
        required:
          - ingress
        properties:
          ingress:
            type: object
            additionalProperties: true
            properties:
              kubernetes:
                type: object
                additionalProperties: false
                required:
                  - enabled
                properties:
                  enabled:
                    type: boolean
    body: |
      componentReleases:
      - name: metallb
        namespace: metallb
        component:
          name: ingress:metallb
          version: 1.0.0
      
      - name: metallb-pool
        namespace: metallb
        component:
          name: ingress:metallb-pool
          version: 1.0.0

      - name: ingress-nginx
        namespace: ingress-nginx
        component:
          name: ingress:ingress-nginx
          version: 1.0.0
      
      {{- if .Context.ingress.kubernetes.enabled }}
      - name: ingress-kubernetes
        namespace: ingress-nginx
        component:
          name: ingress:kubernetes
          version: 1.0.0
      {{- end }}