components:
  - name: ingress-kubernetes
    version: 1.0.0
    source:
      defaultVersion: 0.1.0
      gitRepository:
        name: kad-components
        path: ./charts/ingress-kubernetes/{version}
    contextSchema:
      yaml:
        $schema: "http://json-schema.org/schema#"
        type: object
        additionalProperties: true
        required:
          - ingress
        properties:
          ingress:
            type: object
            additionalProperties: false
            required:
              - url
            properties:
              url:
                type: string
              kubernetes:
                type: object
                additionalProperties: false
                properties:
                  enabled:
                    type: boolean
    dependsOn:
      - ingress
    values: |
      kubernetes:
        enabled: {{ .Context.ingress.kubernetes.enabled }}
        host: kubernetes.{{ .Context.ingress.url }}
      
