components:

  - name: ingress-nginx
    version: 1.0.0
    config:
      timeout: 1m
      install:
        createNamespace: true
        remediation:
          retries: 30
          remediateLastFailure: true
      upgrade:
        remediation:
          retries: 30
          remediateLastFailure: true
    source:
      defaultVersion: 4.10.0
      helmRepository:
        url: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
    contextSchema:
      yaml:
        $schema: "http://json-schema.org/schema#"
        type: object
        additionalProperties: true
        required:
          - ingress
        properties:
          ingress:
            type: object
            additionalProperties: false
            required:
              - url
            properties:
              url:
                type: string
    roles:
      - ingress
      - ingress-nginx
    dependsOn:
      - certManager
      - loadBalancer
    values: |
      controller:
        service:
          annotations:
            metallb.universe.tf/loadBalancerIPs: {{ resolveDNS .Context.ingress.url }}
            metallb.universe.tf/allow-shared-ip: "ingress"
        extraArgs:
          enable-ssl-passthrough: true
